START_OF_SLOT_NAME= '<SOSN>'
END_OF_SLOT_NAME= '<EOSN>'
START_OF_ENTITY= '<SOE>'
END_OF_ENTITY= '<EOE>'
START_OF_TEMPLATE='<SOT>'
END_OF_TEMPLATE= '<EOT>'
SPECIAL_TOKENS = [START_OF_SLOT_NAME, END_OF_SLOT_NAME, START_OF_ENTITY, END_OF_ENTITY, START_OF_TEMPLATE, END_OF_TEMPLATE]

# these variables are for decoding
SLOT_NAME_TAG=0
ENTITY_TAG=1

ROLE_FILLER_ENTITY_EXTRACTION='ree'
EVENT_TEMPLATE_EXTRACTION='ete'
BINARY_RELATION_EXTRACTION='bre'
FOUR_ARY_RELATION_EXTRACTION='4re'

PERP_IND='PerpInd'
PERP_ORG='PerpOrg'
TARGET='Target'
VICTIM='Victim'
WEAPON='Weapon'
REE_ROLES = [PERP_IND, PERP_ORG, TARGET, VICTIM, WEAPON]
